### ISSUE TITLE
Criacao de pagina sobre

### ISSUE THREAD

**Issue by FCGUIMA** [fernandocguimaraes/github-master#3]
Voces poderiram criar uma de sobre? Agradeco

**Comment by fernandocguimaraes** [comment]
A pagina está em producao

**Comment by FCGUIMA** [comment]
Obrigado. Estou aguardando
 
 



De: "fernandocguimaraes" ***@***.***>
Enviada: 2022/03/08 22:07:42
Para: ***@***.***
Cc:  ***@***.***, ***@***.***
Assunto:  Re: [fernandocguimaraes/github-master] Criacao de pagina sobre (Issue #3)
 

 

A pagina está em producao

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
You are receiving this because you authored the thread.Message ID: ***@***.***>

[ { ***@***.***": "http://schema.org", ***@***.***": "EmailMessage", "potentialAction": { ***@***.***": "ViewAction", "target": "https://github.com/fernandocguimaraes/github-master/issues/3#issuecomment-1062448831", "url": "https://github.com/fernandocguimaraes/github-master/issues/3#issuecomment-1062448831", "name": "View Issue" }, "description": "View this Issue on GitHub", "publisher": { ***@***.***": "Organization", "name": "GitHub", "url": "https://github.com" } } ]
